# Generated by Django 2.1.15 on 2020-07-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_dataset_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual', models.TextField()),
                ('data', models.TextField()),
                ('method', models.CharField(max_length=60)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Dataset')),
            ],
        ),
    ]
