# Generated by Django 2.2.10 on 2020-10-22 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201022_2316'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=60)),
                ('exec_time', models.TextField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Dataset')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Result')),
            ],
        ),
    ]
