# Generated by Django 2.2.10 on 2020-10-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_executionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Result'),
        ),
    ]
