# Generated by Django 2.2.10 on 2020-10-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201022_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Dataset'),
        ),
    ]
