# Generated by Django 2.2.10 on 2020-10-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201023_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='data',
        ),
        migrations.RemoveField(
            model_name='result',
            name='visual',
        ),
        migrations.AddField(
            model_name='result',
            name='matplt_3d',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='result',
            name='parallel_centroids',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='result',
            name='parallel_coord',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='result',
            name='pca_3d',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='result',
            name='tsne_3d',
            field=models.TextField(default=''),
        ),
    ]
