# Generated by Django 2.2.10 on 2020-10-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201025_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executionlog',
            old_name='error',
            new_name='error_message',
        ),
    ]
