# Generated by Django 2.2.10 on 2020-10-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201025_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionlog',
            name='error_message',
        ),
    ]
