# Generated by Django 2.1.15 on 2020-06-27 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attribute_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.DateTimeField(verbose_name='date published')),
                ('attributes', models.ManyToManyField(to='app.Attribute')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='records',
            field=models.ManyToManyField(to='app.Record'),
        ),
    ]
