# Generated by Django 2.1.15 on 2020-06-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
