# Generated by Django 2.1.15 on 2020-06-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200627_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Dataset'),
        ),
    ]
